### ISSUE TITLE
yarn run dev faild

### ISSUE THREAD

**Issue by AdeSupriyadi** [cyruzin/codeigniter-react-boilerplate#7]
not running

![image](https://user-images.githubusercontent.com/14267724/78454922-60081a00-76c5-11ea-864d-b24b3ce05b70.png)

trying :

`npm install babel-core babel-loader --save-dev`

no lucky

**Comment by cyruzin** [comment]
Hey man, I'll look into it today.

**Comment by cyruzin** [comment]
Hey man, problem solved! Do a git pull to get the last update and thanks for report this issue.

Closed on: https://github.com/cyruzin/codeigniter-react-boilerplate/commit/e5d632a2004b0c34804d3d963b1140dd42967c05.
